// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimCompaniesOptimizer.Database;

#nullable disable

namespace SimCompaniesOptimizer.Migrations
{
    [DbContext(typeof(SimCompaniesDbContext))]
    [Migration("20211211204529_Fixes")]
    partial class Fixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SimCompaniesOptimizer.Models.ExchangeTracker.ExchangeTrackerEntry", b =>
                {
                    b.Property<string>("Empty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Empty2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangePrices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("TEXT");

                    b.ToTable("ExchangeTrackerEntries");
                });

            modelBuilder.Entity("SimCompaniesOptimizer.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentExchangePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceCard")
                        .HasColumnType("jsonb");

                    b.Property<double>("ProducedAnHour")
                        .HasColumnType("REAL");

                    b.Property<string>("ProducedFrom")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Transportation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
